# Generated by Django 4.2.9 on 2024-02-14 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ts_visualizer", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="magneticfielddata",
            name="x",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="magneticfielddata",
            name="y",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="magneticfielddata",
            name="z",
            field=models.FloatField(null=True),
        ),
    ]
